Repository tgmendes/hello-argo, pull requests merged in 2021-08, with the labels that each got.

#1 trigger deployment if tests are successful
  .github/workflows/go.yml
Labels: svc-argo, env-argo

#5 customise gif params
  .github/workflows/go.yml
  app/car_value.go
Labels: env-avocado, env-coconut, svc-hello, svc-car-value

#6 add condition for label present
  .github/workflows/go.yml
  .github/workflows/push.yml
Labels: env-avocado, all-apps, svc-hello, svc-car-value

#7 add push to main as build condition
  .github/workflows/go.yml
  .github/workflows/push.yml
Labels: env-avocado, svc-hello, svc-car-value

#9 try another thing
  .github/workflows/go.yml
Labels: env-avocado, env-coconut, all-envs, svc-hello, svc-car-value

#11 fix root model
  app/car_value.go
Labels: env-coconut, svc-car-value

#12 test the merge action
  .github/workflows/merge.yml
Labels: all-envs

#13 test the merge action take 2
  .github/workflows/merge.yml
Labels: all-envs

#15 test the merge action take 3
  .github/workflows/go.yml
  .github/workflows/merge.yml
Labels: all-envs

#14 test comment deploy
  .github/workflows/go.yml
Labels: env-coconut

#18 comment
  .github/workflows/go.yml
Labels: env-avocado, svc-car-value, deploy

#8 add new service giffer
  app/giffer.go
  main.go
Labels: env-avocado, env-coconut, svc-giffer

#19 make car text bold
  .github/workflows/go.yml
  app/car_value.go
Labels: env-avocado, svc-car-value

#20 commit hash bold
  .github/workflows/go.yml
  app/car_value.go
Labels: env-avocado, svc-car-value

#21 remove bold
  .github/workflows/go.yml
  app/car_value.go
Labels: env-avocado, svc-car-value

#22 add bold back
  .github/workflows/go.yml
  app/car_value.go
Labels: env-avocado, svc-car-value

#23 change the build
  .github/workflows/go.yml
Labels: env-avocado, svc-car-value

#24 more bold
  app/car_value.go
Labels: env-avocado, svc-car-value

#25 small change
  app/car_value.go
Labels: env-avocado, svc-car-value
